project:
  type: website
  output-dir: docs

website:
  title: "Filipe Cavalcanti"
  google-analytics: "G-XJLNF5SHSC"
  navbar:
    background: "#F8F9F9"
    search: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - blog.qmd
 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

lang: pt-BR
language:
  title-block-author-single: "Autor"
  title-block-author-plural: "Autores"
  title-block-published: "Publicado em"
  
editor: visual

