project:
  type: website
  output-dir: docs

website:
  title: "Filipe Cavalcanti"
  google-analytics: "G-XJLNF5SHSC"
  navbar:
    pinned: true
    search: false
    right:
      - href: index.qmd
        text: Página inicial
      - href: publications.qmd
        text: Publicações
      - href: about.qmd
        text: Sobre
 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

lang: pt-BR
language:
  title-block-author-single: "Autor"
  title-block-author-plural: "Autores"
  title-block-published: "Publicado em"
  
editor: visual

