---
title: "About"
---

### Education

**PhD Student in Economics** (2023-2025) <br> Fundação Getúlio Vargas - Escola de Economia de São Paulo

**M.A. in Economics** (2020-2022) <br> Fundação Getúlio Vargas - Escola de Economia de São Paulo

**B.A. in Economics** (2016-2019) <br> Universidade Federal de Pernambuco

### Work Positions

**Consultant** \@ Inter-American Development Bank\
Dec. 2021 - Current

**Research Associate** \@ J-PAL\
Dec. 2021 - Current

**Consultant** \@ Instituto Sou da Paz\
May 2021 - Sep. 2021

### Academic Positions

Research Assistant \@ Fundação Getúlio Vargas EAESP  (Oct. 2022 - Dec. 2023) <br> Research Assistant \@ Fundação Getúlio Vargas EESP  (Mar. 2021 - May. 2021) <br> Research Assistant \@ Fundação Instituto de Pesquisas Econômicas (Jan. 2021 - Oct. 2021)<br> Junior Researcher \@ PET Economia UFPE (May 2016 - Dec. 2019)

### TA positions

Linear Algebra \@ UFPE (2018, Undergraduate level) <br> Optimization \@ UFPE (2018, Undergraduate level) <br>Calculus I \@ UFPE (2019, Undergraduate level)<br> Statistics \@ FGV EESP (2020, Undergraduate level) <br> Microeconomics II \@ FGV EESP (2021, Graduate level) <br> Microeconometrics II \@ FGV EESP (2021, Graduate level)

### 
