---
title: "Pesquisa"
---

### Publicações

------------------------------------------------------------------------

-   [[**Qualidade da informação sobre recursos federais alocados por emendas parlamentares (2014-2024)**]{.underline}](https://repositorio.ipea.gov.br/entities/publication/a34e8c7f-2282-4789-be78-198b0122a161) (com Fabiola Vieira) -- **Texto para discussão - Ipea** (2025)

-   [[**Pesquisa Assistência Farmacêutica no SUS: gasto em medicamentos judicializados de estados e municípios participantes (2019-2023)**]{.underline}](https://repositorio.ipea.gov.br/handle/11058/17238) (com Fabiola Vieira, Elton Chaves, Karen Costa, Heber Bernarde, Liliane Bernardes e Blenda Pereira) -- **Texto para discussão - Ipea** (2025)

-   [[**Pesquisa Assistência Farmacêutica no SUS: uma síntese dos principais resultados para gestores de saúde (2019-2023)**]{.underline}](https://www.conass.org.br/biblioteca/pesquisa-assistencia-farmaceutica-no-sus/) (com Fabiola Vieira, Elton Chaves, Karen Costa, Heber Bernarde, Liliane Bernardes e Blenda Pereira) -- **Publicação conjunta Ipea, Conass e Conasems** (2025)

-   [[**COVID-19 and violence against women: current knowledge, gaps, and implications for public policy**]{.underline}](https://www.sciencedirect.com/science/article/abs/pii/S0305750X23002796) (com Paula Pereda, Maria Dolores Diaz, Fabiana Rocha, Rodrigo Serra, Isadora Árabe, Samuel Lordemus, e Noemi Kreif) -- **World Development** (2024)

-   [[**The spatial association between drugs and urban violence: an analysis for the Metropolitan Region of Recife, Brazil**]{.underline}](https://www.tandfonline.com/doi/abs/10.1080/17421772.2023.2186474) (com Raul Silveira Neto e Diego Firmino) -- **Spatial Economic Analysis** (2023)

-   [[**Scaling up PrEP: evidence from a policy to prevent HIV in Brazil**]{.underline}](https://bibliotecadigital.fgv.br/dspace/handle/10438/32015) -- **Dissertação de mestrado - FGV EESP** (2022)

\

### Trabalhos em andamento

------------------------------------------------------------------------

-   [[**Building Future-proof Skills for Youth Employment**]{.underline}](https://www.dropbox.com/scl/fi/j4c1dlpffdeg75s94er88/pap_online_version.pdf?rlkey=a3z5ujd1hb91icbqm41dswerx&dl=0) (com Luiz Felipe Fontes e Bruno Ferman) -- Pre-results accepted at **Journal of Development Economics**

-   [[**Financiamento do SUS e emendas parlamentares: uma análise da desigualdade de transferências de incremento ao custeio no período de 2019 a 2024**]{.underline}](https://repositorio.ipea.gov.br/entities/publication/197a02cc-fe09-4754-8319-a679de139c0a) -- **Texto para discussão - Ipea** (2025)\
    Cobertura: [UOL](https://noticias.uol.com.br/colunas/natalia-portinari/2025/08/11/hospitais-particulares-recebem-30-de-emendas-do-atendimento-especializado.htm)

-   [**A representação de pessoas trans nas bases de dados oficiais do Brasil**]{.underline} (com Alberto Filho e Felipe Pateo) -- **Texto para discussão - Ipea** (2025)

-   [**A inserção de pessoas trans no assalariamento formal**]{.underline} (com Alberto Filho e Felipe Pateo) -- **Boletim de mercado de trabalho - Ipea** (2025)

-   [**Boletim de políticas sociais: Saúde**]{.underline} (com Fabiola Vieira, Liliane Bernardes e Sérgio Piola) - **Ipea** (2025)\

### Outros

------------------------------------------------------------------------

-   [[**Avaliação dos modelos regulatórios para a implementação de medidores inteligentes no sistema de distribuição brasileiro**]{.underline}](https://antigo.aneel.gov.br/web/guest/tomadas-de-subsidios?p_auth=nRLZfCTs&p_p_id=participacaopublica_WAR_participacaopublicaportlet&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&p_p_col_id=column-2&p_p_col_count=1&_participacaopublica_WAR_participacaopublicaportlet_ideParticipacaoPublica=3869&_participacaopublica_WAR_participacaopublicaportlet_javax.portlet.action=visualizarParticipacaoPublica) (com [Siglasul](http://www.siglasul.com.br/), [PSR](https://www.psr-inc.com/pt-br/), [ANEEL](https://www.gov.br/aneel/pt-br), e [GIZ](https://www.giz.de/en/worldwide/12055.html)) – [Estudo 1](https://antigo.aneel.gov.br/web/guest/tomadas-de-subsidios?p_p_id=participacaopublica_WAR_participacaopublicaportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_cacheability=cacheLevelPage&p_p_col_id=column-2&p_p_col_count=1&_participacaopublica_WAR_participacaopublicaportlet_ideDocumento=53471&_participacaopublica_WAR_participacaopublicaportlet_tipoFaseReuniao=fase&_participacaopublica_WAR_participacaopublicaportlet_jspPage=%2Fhtml%2Fpp%2Fvisualizar.jsp) \| [Estudo 2](https://antigo.aneel.gov.br/web/guest/tomadas-de-subsidios?p_p_id=participacaopublica_WAR_participacaopublicaportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_cacheability=cacheLevelPage&p_p_col_id=column-2&p_p_col_count=1&_participacaopublica_WAR_participacaopublicaportlet_ideDocumento=53472&_participacaopublica_WAR_participacaopublicaportlet_tipoFaseReuniao=fase&_participacaopublica_WAR_participacaopublicaportlet_jspPage=%2Fhtml%2Fpp%2Fvisualizar.jsp) \| [Estudo 3](https://antigo.aneel.gov.br/web/guest/tomadas-de-subsidios?p_p_id=participacaopublica_WAR_participacaopublicaportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_cacheability=cacheLevelPage&p_p_col_id=column-2&p_p_col_count=1&_participacaopublica_WAR_participacaopublicaportlet_ideDocumento=53473&_participacaopublica_WAR_participacaopublicaportlet_tipoFaseReuniao=fase&_participacaopublica_WAR_participacaopublicaportlet_jspPage=%2Fhtml%2Fpp%2Fvisualizar.jsp) (2024)

-   [[**Violência armada e racismo (1ª edição)**]{.underline}](https://soudapaz.org/wp-content/uploads/2022/05/Firearm_violence_and_racism-1.pdf) (com [Instituto Sou da Paz](https://soudapaz.org/)) (2022)

-   [[**Evidências sobre políticas de mercado de trabalho e implicações para o Brasil: Qualificação profissional**]{.underline}](https://www.povertyactionlab.org/publication/evidence-labor-market-policies-and-implications-brazil-job-training-programs?lang=en) (com [J-PAL](https://www.povertyactionlab.org/) e [BID](https://www.iadb.org/)) (2022)

-   [[**Evidências sobre políticas de mercado de trabalho e implicações para o Brasil: Assistência à busca por emprego**]{.underline}](https://www.povertyactionlab.org/publication/evidence-labor-market-policies-and-implications-brazil-job-search-assistance?lang=en) (com [J-PAL](https://www.povertyactionlab.org/) e [BID](https://www.iadb.org/)) (2024)

-   [[**Evidências sobre políticas de mercado de trabalho e implicações para o Brasil: Microcrédito**]{.underline}](https://www.povertyactionlab.org/publication/evidence-labor-market-policies-and-implications-brazil-microcredit?lang=en) (com [J-PAL](https://www.povertyactionlab.org/) e [BID](https://www.iadb.org/)) (2024)

-   [**Evidências sobre políticas de mercado de trabalho e implicações para o Brasil: Futuro do trabalho**]{.underline} (com [J-PAL](https://www.povertyactionlab.org/) e [BID](https://www.iadb.org/))

-   [**Evidências sobre políticas de mercado de trabalho e implicações para o Brasil: Treinamento ao empreendedorismo**]{.underline} (com [J-PAL](https://www.povertyactionlab.org/) e [BID](https://www.iadb.org/))

-   [**Evidências sobre políticas de mercado de trabalho e implicações para o Brasil: Informalidade**]{.underline} (com [J-PAL](https://www.povertyactionlab.org/) e [BID](https://www.iadb.org/))